### ISSUE TITLE
Error Massage

### ISSUE THREAD

**Issue by Kenny2k8** [AboutSelphy/Streamer.bot-Automaticly-MutliStream#1]
Hey,

your version check  is not working correctly cause i got the massage  "Failed to retrieve release information: NotFound  " 

if i do it in the Brower  your api i got this :

{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-tags"
}

**Comment by MadeByLukeDEV** [comment]
Thanks, found it out today :) Update is coming. Just disable the first Update check script 
![image](https://github.com/AboutSelphy/Streamer.bot-Automaticly-MutliStream/assets/109421172/3945b4e8-36bb-4f17-853e-f8e2d4dcee36)



Did you use by any chance Timed Action with a low Delay?

**Comment by Kenny2k8** [comment]
I use timed Action every 30 min  

and the action post this error massage

**Comment by MadeByLukeDEV** [comment]
okey thanks :) Right now i fixed some bugs with the Timed Action but couldn't find out now what happend with the script check :/ BUT it should be fixed if the new Streamer.bot Update is coming :)
